### ISSUE TITLE
Plugin now Work :(

### ISSUE THREAD

**Issue by andrewjswan** [yoavain/mediaportal-tunein#4]
I go to the plugin, I get a blank window, can only go back by pressing the H ie home.
```
[2015-09-23 21:04:46,321] [Log    ] [MPMain   ] [INFO ] - PluginManager: 'C:\Team MediaPortal\MediaPortal\Plugins\windows\RadioTimeOpmlApi.dll' file version: 1.4.2.99
...
[2015-09-23 21:04:46,336] [Log    ] [MPMain   ] [INFO ] - PluginManager: 'C:\Team MediaPortal\MediaPortal\Plugins\windows\RadioTimePlugin.dll' file version: 1.4.2.99
```
Error:
```
[2015-09-23 23:14:27,064] [Log    ] [MPMain   ] [DEBUG] - TextureManager: CleanupThumbs()
[2015-09-23 23:14:27,064] [Error  ] [MPMain   ] [ERROR] - SKIN: Missing C:\ProgramData\Team MediaPortal\MediaPortal\Skin\Titan\common.facade.radiotime.xml
[2015-09-23 23:14:27,074] [Log    ] [MPMain   ] [WARN ] - GUIWindow:OnWindowLoaded: 'C:\ProgramData\Team MediaPortal\MediaPortal\Skin\Titan\Themes\ajs Theme\radiotime.xml' is missing control id 50 (window property: listControl)
[2015-09-23 23:14:27,545] [Log    ] [MPMain   ] [DEBUG] - Window: RadioTimePlugin.RadioTimePluginGUI init
[2015-09-23 23:14:27,545] [Log    ] [MPMain   ] [INFO ] - RadioTime page loading :http://opml.radiotime.com/Index.aspx?formats=wma,mp3,aac,real,flash,wmpro,wmvoice,wmvideo,ogg,qt&username=ajs@ukrpost.net&partnerID=41&locale=ru
[2015-09-23 23:14:27,546] [Error  ] [MPMain   ] [ERROR] - OnMessage exception:System.NullReferenceException: Object reference not set to an instance of an object.
   at RadioTimePlugin.RadioTimePluginGUI.UpdateList()
   at RadioTimePlugin.RadioTimePluginGUI.OnPageLoad()
   at MediaPortal.GUI.Library.GUIWindow.OnMessage(GUIMessage message)
[2015-09-23 23:14:29,083] [Log    ] [MPMain   ] [DEBUG] - D3D: Showing mouse cursor
[2015-09-23 23:14:29,083] [Log    ] [MPMain   ] [DEBUG] - D3D: Cursor ShowMouseCursor state 1
[2015-09-23 23:14:29,083] [Log    ] [MPMain   ] [DEBUG] - D3D: OnPaint()
[2015-09-23 23:14:29,216] [Log    ] [MPMain   ] [ERROR] - Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at RadioTimePlugin.RadioTimePluginGUI.UpdateGui()
   at RadioTimePlugin.RadioTimePluginGUI.OnAction(Action action)
   at MediaPortal.GUI.Library.GUIWindowManager.OnAction(Action action)
   at MediaPortalApp.OnAction(Action action)  Message: Object reference not set to an instance of an object.  Site   : Void UpdateGui()  Source : RadioTimePlugin  Stack Trace:     at RadioTimePlugin.RadioTimePluginGUI.UpdateGui()
   at RadioTimePlugin.RadioTimePluginGUI.OnAction(Action action)
   at MediaPortal.GUI.Library.GUIWindowManager.OnAction(Action action)
   at MediaPortalApp.OnAction(Action action)
[2015-09-23 23:14:29,218] [Error  ] [MPMain   ] [ERROR] - Exception: Object reference not set to an instance of an object. RadioTimePlugin    at RadioTimePlugin.RadioTimePluginGUI.UpdateGui()
   at RadioTimePlugin.RadioTimePluginGUI.OnAction(Action action)
   at MediaPortal.GUI.Library.GUIWindowManager.OnAction(Action action)
   at MediaPortalApp.OnAction(Action action)
[2015-09-23 23:14:29,220] [Log    ] [MPMain   ] [ERROR] - Exception: System.Exception: exception occurred ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at RadioTimePlugin.RadioTimePluginGUI.UpdateGui()
   at RadioTimePlugin.RadioTimePluginGUI.OnAction(Action action)
   at MediaPortal.GUI.Library.GUIWindowManager.OnAction(Action action)
   at MediaPortalApp.OnAction(Action action)
   --- End of inner exception stack trace ---
   at MediaPortalApp.OnAction(Action action)
   at MediaPortal.GUI.Library.OnActionHandler.Invoke(Action action)
   at MediaPortal.GUI.Library.GUIWindowManager.DispatchThreadMessages()
   at MediaPortalApp.FrameMove()  Message: exception occurred  Site   : Void OnAction(MediaPortal.GUI.Library.Action)  Source : MediaPortal  Inner Exception(s):  -> exception occurred  -> Object reference not set to an instance of an object.  Stack Trace:     at MediaPortalApp.OnAction(Action action)
   at MediaPortal.GUI.Library.OnActionHandler.Invoke(Action action)
   at MediaPortal.GUI.Library.GUIWindowManager.DispatchThreadMessages()
   at MediaPortalApp.FrameMove()
[2015-09-23 23:14:29,836] [Log    ] [MPMain   ] [ERROR] - Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at RadioTimePlugin.RadioTimePluginGUI.UpdateGui()
   at RadioTimePlugin.RadioTimePluginGUI.OnAction(Action action)
   at MediaPortal.GUI.Library.GUIWindowManager.OnAction(Action action)
   at MediaPortalApp.OnAction(Action action)  Message: Object reference not set to an instance of an object.  Site   : Void UpdateGui()  Source : RadioTimePlugin  Stack Trace:     at RadioTimePlugin.RadioTimePluginGUI.UpdateGui()
   at RadioTimePlugin.RadioTimePluginGUI.OnAction(Action action)
   at MediaPortal.GUI.Library.GUIWindowManager.OnAction(Action action)
   at MediaPortalApp.OnAction(Action action)
[2015-09-23 23:14:29,836] [Error  ] [MPMain   ] [ERROR] - Exception: Object reference not set to an instance of an object. RadioTimePlugin    at RadioTimePlugin.RadioTimePluginGUI.UpdateGui()
   at RadioTimePlugin.RadioTimePluginGUI.OnAction(Action action)
   at MediaPortal.GUI.Library.GUIWindowManager.OnAction(Action action)
   at MediaPortalApp.OnAction(Action action)
[2015-09-23 23:14:29,838] [Log    ] [MPMain   ] [ERROR] - Exception: System.Exception: exception occurred ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at RadioTimePlugin.RadioTimePluginGUI.UpdateGui()
   at RadioTimePlugin.RadioTimePluginGUI.OnAction(Action action)
   at MediaPortal.GUI.Library.GUIWindowManager.OnAction(Action action)
   at MediaPortalApp.OnAction(Action action)
   --- End of inner exception stack trace ---
   at MediaPortalApp.OnAction(Action action)
   at MediaPortal.GUI.Library.OnActionHandler.Invoke(Action action)
   at MediaPortal.GUI.Library.GUIWindowManager.DispatchThreadMessages()
   at MediaPortalApp.FrameMove()  Message: exception occurred  Site   : Void OnAction(MediaPortal.GUI.Library.Action)  Source : MediaPortal  Inner Exception(s):  -> exception occurred  -> Object reference not set to an instance of an object.  Stack Trace:     at MediaPortalApp.OnAction(Action action)
   at MediaPortal.GUI.Library.OnActionHandler.Invoke(Action action)
   at MediaPortal.GUI.Library.GUIWindowManager.DispatchThreadMessages()
   at MediaPortalApp.FrameMove()
[2015-09-23 23:14:29,965] [Log    ] [MPMain   ] [ERROR] - Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at RadioTimePlugin.RadioTimePluginGUI.UpdateGui()
   at RadioTimePlugin.RadioTimePluginGUI.OnAction(Action action)
   at MediaPortal.GUI.Library.GUIWindowManager.OnAction(Action action)
   at MediaPortalApp.OnAction(Action action)  Message: Object reference not set to an instance of an object.  Site   : Void UpdateGui()  Source : RadioTimePlugin  Stack Trace:     at RadioTimePlugin.RadioTimePluginGUI.UpdateGui()
   at RadioTimePlugin.RadioTimePluginGUI.OnAction(Action action)
   at MediaPortal.GUI.Library.GUIWindowManager.OnAction(Action action)
   at MediaPortalApp.OnAction(Action action)
[2015-09-23 23:14:29,967] [Error  ] [MPMain   ] [ERROR] - Exception: Object reference not set to an instance of an object. RadioTimePlugin    at RadioTimePlugin.RadioTimePluginGUI.UpdateGui()
   at RadioTimePlugin.RadioTimePluginGUI.OnAction(Action action)
   at MediaPortal.GUI.Library.GUIWindowManager.OnAction(Action action)
   at MediaPortalApp.OnAction(Action action)
[2015-09-23 23:14:29,969] [Log    ] [MPMain   ] [ERROR] - Exception: System.Exception: exception occurred ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at RadioTimePlugin.RadioTimePluginGUI.UpdateGui()
   at RadioTimePlugin.RadioTimePluginGUI.OnAction(Action action)
   at MediaPortal.GUI.Library.GUIWindowManager.OnAction(Action action)
   at MediaPortalApp.OnAction(Action action)
   --- End of inner exception stack trace ---
   at MediaPortalApp.OnAction(Action action)
   at MediaPortal.GUI.Library.OnActionHandler.Invoke(Action action)
   at MediaPortal.GUI.Library.GUIWindowManager.DispatchThreadMessages()
   at MediaPortalApp.FrameMove()  Message: exception occurred  Site   : Void OnAction(MediaPortal.GUI.Library.Action)  Source : MediaPortal  Inner Exception(s):  -> exception occurred  -> Object reference not set to an instance of an object.  Stack Trace:     at MediaPortalApp.OnAction(Action action)
   at MediaPortal.GUI.Library.OnActionHandler.Invoke(Action action)
   at MediaPortal.GUI.Library.GUIWindowManager.DispatchThreadMessages()
   at MediaPortalApp.FrameMove()
[2015-09-23 23:14:30,053] [Log    ] [MPMain   ] [ERROR] - Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at RadioTimePlugin.RadioTimePluginGUI.UpdateGui()
   at RadioTimePlugin.RadioTimePluginGUI.OnAction(Action action)
   at MediaPortal.GUI.Library.GUIWindowManager.OnAction(Action action)
   at MediaPortalApp.OnAction(Action action)  Message: Object reference not set to an instance of an object.  Site   : Void UpdateGui()  Source : RadioTimePlugin  Stack Trace:     at RadioTimePlugin.RadioTimePluginGUI.UpdateGui()
   at RadioTimePlugin.RadioTimePluginGUI.OnAction(Action action)
   at MediaPortal.GUI.Library.GUIWindowManager.OnAction(Action action)
   at MediaPortalApp.OnAction(Action action)
[2015-09-23 23:14:30,054] [Error  ] [MPMain   ] [ERROR] - Exception: Object reference not set to an instance of an object. RadioTimePlugin    at RadioTimePlugin.RadioTimePluginGUI.UpdateGui()
   at RadioTimePlugin.RadioTimePluginGUI.OnAction(Action action)
   at MediaPortal.GUI.Library.GUIWindowManager.OnAction(Action action)
   at MediaPortalApp.OnAction(Action action)
[2015-09-23 23:14:30,055] [Log    ] [MPMain   ] [ERROR] - Exception: System.Exception: exception occurred ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at RadioTimePlugin.RadioTimePluginGUI.UpdateGui()
   at RadioTimePlugin.RadioTimePluginGUI.OnAction(Action action)
   at MediaPortal.GUI.Library.GUIWindowManager.OnAction(Action action)
   at MediaPortalApp.OnAction(Action action)
   --- End of inner exception stack trace ---
   at MediaPortalApp.OnAction(Action action)
   at MediaPortal.GUI.Library.OnActionHandler.Invoke(Action action)
   at MediaPortal.GUI.Library.GUIWindowManager.DispatchThreadMessages()
   at MediaPortalApp.FrameMove()  Message: exception occurred  Site   : Void OnAction(MediaPortal.GUI.Library.Action)  Source : MediaPortal  Inner Exception(s):  -> exception occurred  -> Object reference not set to an instance of an object.  Stack Trace:     at MediaPortalApp.OnAction(Action action)
   at MediaPortal.GUI.Library.OnActionHandler.Invoke(Action action)
   at MediaPortal.GUI.Library.GUIWindowManager.DispatchThreadMessages()
   at MediaPortalApp.FrameMove()
[2015-09-23 23:14:30,220] [Log    ] [MPMain   ] [ERROR] - Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at RadioTimePlugin.RadioTimePluginGUI.UpdateGui()
   at RadioTimePlugin.RadioTimePluginGUI.OnAction(Action action)
   at MediaPortal.GUI.Library.GUIWindowManager.OnAction(Action action)
   at MediaPortalApp.OnAction(Action action)  Message: Object reference not set to an instance of an object.  Site   : Void UpdateGui()  Source : RadioTimePlugin  Stack Trace:     at RadioTimePlugin.RadioTimePluginGUI.UpdateGui()
   at RadioTimePlugin.RadioTimePluginGUI.OnAction(Action action)
   at MediaPortal.GUI.Library.GUIWindowManager.OnAction(Action action)
   at MediaPortalApp.OnAction(Action action)
[2015-09-23 23:14:30,222] [Error  ] [MPMain   ] [ERROR] - Exception: Object reference not set to an instance of an object. RadioTimePlugin    at RadioTimePlugin.RadioTimePluginGUI.UpdateGui()
   at RadioTimePlugin.RadioTimePluginGUI.OnAction(Action action)
   at MediaPortal.GUI.Library.GUIWindowManager.OnAction(Action action)
   at MediaPortalApp.OnAction(Action action)
[2015-09-23 23:14:30,224] [Log    ] [MPMain   ] [ERROR] - Exception: System.Exception: exception occurred ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at RadioTimePlugin.RadioTimePluginGUI.UpdateGui()
   at RadioTimePlugin.RadioTimePluginGUI.OnAction(Action action)
   at MediaPortal.GUI.Library.GUIWindowManager.OnAction(Action action)
   at MediaPortalApp.OnAction(Action action)
   --- End of inner exception stack trace ---
   at MediaPortalApp.OnAction(Action action)
   at MediaPortal.GUI.Library.OnActionHandler.Invoke(Action action)
   at MediaPortal.GUI.Library.GUIWindowManager.DispatchThreadMessages()
   at MediaPortalApp.FrameMove()  Message: exception occurred  Site   : Void OnAction(MediaPortal.GUI.Library.Action)  Source : MediaPortal  Inner Exception(s):  -> exception occurred  -> Object reference not set to an instance of an object.  Stack Trace:     at MediaPortalApp.OnAction(Action action)
   at MediaPortal.GUI.Library.OnActionHandler.Invoke(Action action)
   at MediaPortal.GUI.Library.GUIWindowManager.DispatchThreadMessages()
   at MediaPortalApp.FrameMove()
[2015-09-23 23:14:36,246] [Log    ] [MPMain   ] [DEBUG] - D3D: Hiding mouse cursor
```

**Comment by andrewjswan** [comment]
Missing common.facade.radiotime.xml :(
